# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Toughts
tagline:          'Will you listen?'
description:      '@Skurken.se you have the possibility to follow some of the worth to mention toughts brought to life from studying the field of Computer Science.'
url:              https://skurken.se
baseurl:          /

author:
  name:           'Sebastian Lhådö'
  url:            https://linkedin.com/in/sebastianlhado

paginate:         2

# Custom vars
github:
  repo:           https://github.com/miniskurken
