# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Miniskurken
tagline:          'Waist deep in studies'
description:      '@Skurken.se you have the possibility to follow some of the worth to mention tought brought to life during my time as a student.'
url:              https://skurken.se
baseurl:          /

author:
  name:           'Sebastian Lhådö'
  url:            https://linkedin.com/in/sebastianlhado

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/miniskurken
